check ae, vae todo vaegan,irl,lstm
traja-team/traja pull request #25
Opened 2020-11-28 18:44 UTC by WolfByttner

Creating PR for bookkeeping

2020-11-28 21:25 UTC, WolfByttner reviewed
I think it'd be good if there was an example (in the docs or otherwise) of how to run all of this. Currently there seems to be several functions (Trainer comes to mind) that do the same thing and the relation between them aren't clear. Some additional structure, comments and examples would go a long way towards making this commit easier to understand.

2020-11-29 22:21 UTC, Saran-nns commented on traja/datasets/dataset.py
> +    r""" Data loader object. Wrap Data preprocessors, dataset, sampler and return the data loader object"""
Updated description and let this issue open since, it seems more practical to apply different scalers for each category. Need to be tested

2020-11-29 23:13 UTC, Saran-nns commented on traja/models/ae.py
> +    """Dense Latent Layer """
Dense Dientangled Latent Layer between encoder and decoder. This layer with disentangled latent learns the individual aspects of the underlying system that generates observations.

2020-11-30 11:12 UTC, Saran-nns commented on traja/models/ae.py
> +        # classifier_out = F.softmax(classifier4)
resolved and removed the dead codes

2020-11-30 11:13 UTC, Saran-nns commented on traja/models/experiment.py
> +class Trainer:
added comments and description for training models using Trainer

2020-11-30 11:17 UTC, Saran-nns commented on traja/models/ae.py
> +        # self.input_size = input_size
Initial idea was to modularize the initialization of class arguments by automatic assigning of parameters using ```def initializer(func)```.  but i guess, it is better to be explicit in this regard, for the sake of readability

2020-11-30 11:20 UTC, Saran-nns commented
Overall, let this PR be open and more updates are on the way

2020-12-10 15:48 UTC, justinshenk requested changes
Add `.vscode` to .gitignore

2020-12-10 15:50 UTC, justinshenk commented on traja/datasets/dataset.py
> +    r"""Pytorch Dataset object
Remove 'r' before docstring, unnecessary

2020-12-11 18:13 UTC, Saran-nns commented on traja/datasets/dataset.py
> +    r"""Pytorch Dataset object
done

2020-12-19 13:34 UTC, Saran-nns commented on traja/datasets/dataset.py
> +    r""" Data loader object. Wrap Data preprocessors, dataset, sampler and return the data loader object"""
applied and resolved the issues in the recent commit and the PR

2021-01-04 14:53 UTC, WolfByttner commented
Commits merged in rebase https://github.com/traja-team/traja/pull/33

2021-01-04 14:53 UTC, closed without merging